version: '3.1'

services:
  mongo:
    image: mongo:4.0
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
      - MONGO_INITDB_DATABASE=${DB}
      - MONGO_INITDB_DATABASE_USERNAME=${DB_USER}
      - MONGO_INITDB_DATABASE_PASSWORD=${DB_PASS}
