version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - ${DB_HOST}:${DB_PORT}:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MONGO_INITDB_DATABASE=${DB}
      - MONGO_INITDB_DATABASE_USERNAME=${DB_USER}
      - MONGO_INITDB_DATABASE_PASSWORD=${DB_PASS}
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
